### PR TITLE
Fix plugin for Sketch 56 and up

### LINKED ISSUE #19: Sketch 59 crashes each time when exporting WITH prototyping links
The plugin is not compatible with the new Sketch version. Using the plugin leads to Sketch crashing each time when you want to export a PDF WITH prototyping links (Without links works).

### PR DESCRIPTION
**Pull request by bomberstudios**
Fixes #19

### CODE REVIEW

File: src/framework/print-export/PESketchMethods.m [hunk 1]
```diff
@@ -79,9 +79,17 @@ + (void)displayFlashMessage:(NSString *)message document:(MSDocument *)document
...
     SEL selector = NSSelectorFromString(@"detachedLayerGroupRecursively:withDocument:visitedSymbols:");
-    typedef id (*MethodType)(MSImmutableSymbolInstance *, SEL, BOOL, MSImmutableDocumentData *, id);
-    MethodType method = (MethodType)[symbolInstance methodForSelector:selector];
-    return method(symbolInstance, selector, recursively, documentData, nil);
+    // This only exists in Sketch 55 and earlier
+    if ([symbolInstance respondsToSelector:selector]) {
+        typedef id (*MethodType)(MSImmutableSymbolInstance *, SEL, BOOL, MSImmutableDocumentData *, NSSet *);
+        MethodType method = (MethodType)[symbolInstance methodForSelector:selector];
+        return method(symbolInstance, selector, recursively, documentData, nil);
+    } else {
```
Comment (christianklotz) [inline src/framework/print-export/PESketchMethods.m]:
```suggestion
    }
```

Since you return if the condition is met you can drop the `else` block and keep the default logic one indentation level more to the left.

**Review by christianklotz — APPROVED** [review]
👍
